### PR TITLE
feat: added support for the setCurrency method

### PR DESCRIPTION
**Pull request by eliascarella**
added support for the setCurrency method and an example of working code. 

In response to issue #26

### CODE REVIEW

**Comment by f3ltron** [comment]
Thank you a lot to take time for it :). I will check today and validate and publish if its all good :)

**Comment by eliascarella** [comment]
> Thank you a lot to take time for it :). I will check today and validate and publish if its all good :)

No worries, let me know how I can improve ! It was my first time contributing to such a project and my code might not be as clean as your codebase. 
Also, I decided to do it wihout integrating it with localization and instead do it as a "standalone" call. It works for my purpose and we could use it this way until someone finds a way to properly integrate it with everything :)

**Comment by f3ltron** [comment]
> > Thank you a lot to take time for it :). I will check today and validate and publish if its all good :)
> 
> No worries, let me know how I can improve ! It was my first time contributing to such a project and my code might not be as clean as your codebase.
> Also, I decided to do it wihout integrating it with localization and instead do it as a "standalone" call. It works for my purpose and we could use it this way until someone finds a way to properly integrate it with everything :)

No worries. Glad you enjoy the codebase. I will have a look after work

**Comment by f3ltron** [comment]
Perfect ! thank you a lot for your work.

close #28

**Pull request merged**
